# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
rojo = "rojo-rbx/rojo@7.4.4"
stylua = "johnnymorganz/stylua@0.20.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.32.4"
lune = "lune-org/lune@0.8.8"
darklua = "seaofvoices/darklua@0.13.1"
asphalt = "jackTabsCode/asphalt@0.8.1"
